portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('webapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from .views import *
app_name = "webapp"
urlpatterns = [
    path('', home, name="home"),
    path('login', login_request, name="login"),
    path('logout', logout_request, name="logout"),
    path('apply', apply_job, name="apply")
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from dashboard.models import Employees
import datetime


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class JobApplyForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['employer', 'firstname', 'lastname', 'email', 'phone_number', 'status', 'availability', 'resume', 'skill', 'experience_year']

webapp/views.py
import json
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.serializers.json import DjangoJSONEncoder
from dashboard.models import Employer
from django.urls import reverse_lazy
from dashboard.db_helper import get_rows
from .forms import UserRegisterForm, JobApplyForm
from django.contrib import messages
from django.http import JsonResponse


def home_data():
    sql = """
        SELECT id, 
            job_title,
            company,
            logo,
            job_description,
            email,
            rate,
            availability,
            duration,
            employment_type,
            status,
            date(created_at) as created_at
        from Employer;
    """
    results = get_rows(sql)
    return json.dumps(results, cls=DjangoJSONEncoder)


# Create your views here.
def home(request):
    # for user login and register
    register_form = UserRegisterForm()
    login_form = AuthenticationForm()
    job_form = JobApplyForm()
    context = {
        'data': home_data(),
        'register_form': register_form,
        'login_form': login_form,
        'job_form': job_form
    }
    return render(request, 'index.html', context=context)


# login / register /logout view
def register_request(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("dashboard:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return redirect("webapp:home")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("dashboard:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            register_form = UserRegisterForm()
            login_form = form
            context = {
                'data': home_data(),
                'register_form': register_form,
                'login_form': login_form
            }
            return render(request, 'index.html', context=context)
    return redirect("webapp:home")


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('webapp:home')


def apply_job(request):
    # TODO Error handling and optimization required

    if request.method == "POST":
        skill1 = request.POST.get("skill1", None)
        nskill1 = request.POST.get("nskill1", None)
        skill2 = request.POST.get("skill2", None)
        nskill2 = request.POST.get("nskill2", None)
        skill3 = request.POST.get("skill3", None)
        nskill3 = request.POST.get("nskill3", None)
        job_id = int(request.POST.get("job_id", None))
        form_data = {
            "employer": Employer.objects.get(id=int(job_id)),
            "firstname": request.POST.get('firstname', ''),
            "lastname": request.POST.get('lastname', ''),
            "email": request.POST.get('email', ''),
            "phone_number": request.POST.get('phone_number', None),
            "status": request.POST.get("status", None),
            "availability": request.POST.get("availability", None)

        }
        skills = [skill1, skill2, skill3]
        years_skills = [nskill1, nskill2, nskill3]
        for skill, years in zip(skills, years_skills):
            if skill is not None and skill != '':
                form_data['skill'] = skill
                form_data['experience_year'] = years
                form = JobApplyForm(form_data, request.FILES)
                if form.is_valid():
                    data = form.save(commit=False)
                    data.employer = Employer.objects.get(id=job_id)
                    data.save()
        # if skill1 is not None:
        #     form_data['skill'] = skill1
        #     form_data['experience_year'] = nskill1
        #     form = JobApplyForm(form_data, request.FILES)
        #     if form.is_valid():
        #         data = form.save(commit=False)
        #         data.employer = Employer.objects.get(id=1)
        #         data.save()

        # if skill2 is not None:
        #     form_data['skill'] = skill2
        #     form_data['experience_year'] = nskill2
        #     form = JobApplyForm(form_data, request.FILES)
        #     if form.is_valid():
        #         data = form.save(commit=False)
        #         data.employer = Employer.objects.get(id=1)
        #         data.save()
        #
        # if skill3 is not None:
        #     form_data['skill'] = skill3
        #     form_data['experience_year'] = nskill3
        #     form = JobApplyForm(form_data, request.FILES)
        #     if form.is_valid():
        #         data = form.save(commit=False)
        #         data.employer = Employer.objects.get(id=1)
        #         data.save()
        return JsonResponse({
            "status_code": 200,
            "message": "job applied successfully.",
            "url": reverse_lazy('webapp:home')
        })
    return redirect("webapp:home")

webapp/templates/index.html
{% extends 'webapp_base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href=" {% static 'css/users.css' %} ">
{% endblock stylesheets %}
{% block body %}
<div class="container-fluid">
<div class="col-lg-12">
{#    <nav class="navbar navbar-expand-lg navbar-light bg-light float-right">#}
{#        <div class="collapse navbar-collapse">#}
{#            <form class="form-inline my-2 my-lg-0" id="search_form">#}
{#                <input class="form-control mr-sm-2" type="search" placeholder="Skills"  value='' aria-label="Search" name="skills">#}
{#                <input class="form-control mr-sm-2" type="search" placeholder="Number of years" value='' aria-label="Search" name="years">#}
{#                <input class="form-control mr-sm-2" type="search" placeholder="lastname" value="" aria-label="Search" name="lastname">#}
{#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="searchbar_button">Search</button>#}
{#            </form>#}
{#        </div>#}
{#    </nav>#}
    <br>
    <br>
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Candidates <b>Portal</b></h2>
                </div>
                <div class="col-sm-6">
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover" id="user_dataTable">
        </table>
    </div>
    <div id="applyJob" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="apply_job_form" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="modal-header">
                        <h4 class="modal-title">Apply for a Job</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Firstname</label>
                            <input id="{{ job_form.firstname.id_for_label }}" type="text" class="form-control" name="{{ job_form.firstname.name }}" required>
                        </div>
                        <div class="form-group">
                            <label>Lastname</label>
                            <input type="text" id="{{ job_form.lastname.id_for_label }}" class="form-control" name="{{ job_form.lastname.name }}" required>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" id="{{ job_form.email.id_for_label }}" class="form-control" name="{{ job_form.email.name }}" required>
                        </div>
                        <div class="form-group">
                            <label>Mobile Phone</label>
                            <input type="text" id="{{ job_form.phone_number.id_for_label }}" class="form-control" name="{{ job_form.phone_number.name }}" required>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col">
                                    <label class="font-weight-bold">Skill Name</label>
                                </div>
                                <div class="col">
                                    <label class="font-weight-bold">Years of Experience</label>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="skill 1..." name="skill1">
                                </div>
                                <div class="col">
                                    <input type="number" min="0" value="0" class="form-control" placeholder="skill1_years" name="nskill1">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="skill 2..." name="skill2">
                                </div>
                                <div class="col">
                                    <input type="number" min="0" value="0" class="form-control" placeholder="skill2_years" name="nskill2">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="skill 3..." name="skill3">
                                </div>
                                <div class="col">
                                    <input type="number" min="0" value="0" class="form-control" placeholder="skill3_years" name="nskill3">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <select class="form-control" id="{{ job_form.status.id_for_label }}" aria-label="Status select" name="{{ job_form.status.name }}">
                                <option value="None" selected>None</option>
                                <option value="International Students">International Student</option>
                                <option value="PR / Citizen">PR / Citizen</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Availability</label>
                            <select class="form-control" id="{{ job_form.availability.id_for_label }}" name="{{ job_form.availability.name }}">
                                <option value="None" selected>None</option>
                                <option value="Full Time">Full Time</option>
                                <option value="Part Time">Part Time</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Upload Resume</label>
                            <input type="file" class="form-control" name="{{ job_form.resume.name }}" id="resume" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" id="cancel_job_button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" id="apply_job_button" class="btn btn-success" value="Apply">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

</div>

{% endblock body %}

{% block scripts %}
    <script src="{% static 'js/home.js' %}"></script>
    <script>
        $(document).ready(function(){
            let data = {{ data|safe }};
            handler(data);
        });
    </script>
{% endblock scripts %}

webapp/templates/webapp_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% block stylesheets %}
    {% endblock stylesheets %}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <a class="navbar-brand" href=".">Job Portal</a>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            Welcome {{ request.user.username }}
                            <a href="{% url 'webapp:logout' %}">
                                <button class="btn btn-outline-success my-2 my-sm-0">Logout</button>
                            </a>
                        {% else %}
                            <button id="loginRegisterButton" class="btn btn-outline-success my-2 my-sm-0" type="submit">Login/Register</button>
                        {% endif %}
            </li>
        </ul>
    </div>
</nav>

<br>
{% block body %}
{% endblock body %}


<!-- Login / Register -->
<!--Modal: Login / Register Form-->
<div class="modal fade" id="loginRegisterModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog cascading-modal" role="document">
    <!--Content-->
    <div class="modal-content">

      <!--Modal cascading tabs-->
      <div class="modal-c-tabs">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs md-tabs tabs-2 light-blue darken-3" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#panel7" role="tab"><i class="fas fa-user mr-1"></i>
              Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#panel8" role="tab"><i class="fas fa-user-plus mr-1"></i>
              Register</a>
          </li>
        </ul>

        <!-- Tab panels -->
        <div class="tab-content">
          <!--Panel 7-->
          <div class="tab-pane fade in show active" id="panel7" role="tabpanel">

            <!--Body-->
            <div class="modal-body mb-1">
                <form action="{% url 'webapp:login' %}" method="post">
                    {% csrf_token %}
                    <div>
                        {% if login_form.errors %}
                            {% for field in login_form %}
                            {% for error in field.errors %}
                              <div class="alert alert-danger">
                                   <strong>{{ error|escape }}</strong>
                              </div>
                           {% endfor %}
                       {% endfor %}
                    {% endif %}
                    </div>
                    <div class="md-form form-sm mb-5">
                        <i class="fas fa-envelope prefix"></i>
                        <input type="text" id="{{ login_form.username.id_for_label }}" class="form-control form-control-sm validate" name="{{login_form.username.name}}" required>
                        <label data-error="wrong" data-success="right" for="{{ login_form.username.id_for_label }}">Your username</label>
                    </div>

                    <div class="md-form form-sm mb-4">
                        <i class="fas fa-lock prefix"></i>
                        <input type="password" id="{{ login_form.password.id_for_label }}" class="form-control form-control-sm validate" name="{{ login_form.password.name }}" required>
                        <label data-error="wrong" data-success="right" for="{{ login_form.password.id_for_label }}">Your password</label>
                    </div>
                    <div class="text-center mt-2">
                        <button class="btn btn-info">Log in <i class="fas fa-sign-in ml-1"></i></button>
                    </div>
                </form>
            </div>
            <!--Footer-->
            <div class="modal-footer">
{#              <div class="options text-center text-md-right mt-1">#}
{#                <p>Not a member? <a href="#" class="blue-text">Sign Up</a></p>#}
{#                <p>Forgot <a href="#" class="blue-text">Password?</a></p>#}
{#              </div>#}
              <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Close</button>
            </div>

          </div>
          <!--/.Panel 7-->

          <!--Panel 8-->
          <div class="tab-pane fade" id="panel8" role="tabpanel">
            <!--Body-->
            <div class="modal-body">

                <div class="text-center form-sm mt-2">
                    <button class="btn btn-info">Sign up As a Job Candidate <i class="fas fa-sign-in ml-1"></i></button>
                    <button class="btn btn-info">Sign up as a Employer <i class="fas fa-sign-in ml-1"></i></button>
                </div>

            </div>
            <!--Footer-->
            <div class="modal-footer">
{#              <div class="options text-right">#}
{#                <p class="pt-1">Already have an account? <a href="#panel7" class="blue-text" data-toggle="tab">Log In</a></p>#}
{#              </div>#}
              <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Close</button>
            </div>
          </div>
          <!--/.Panel 8-->
        </div>

      </div>
    </div>
    <!--/.Content-->
  </div>
</div>




<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
{% block scripts %} {% endblock scripts %}

<script>
    $(document).ready(function() {
        $("#loginRegisterButton").on("click", function(e){
           $("#loginRegisterModalForm").modal('show');
           e.preventDefault();
           e.stopImmediatePropagation();
        });
    });
</script>
</body>
</html>