dashboard/urls.py
from django.urls import path
from .views import *

app_name = "dashboard"
urlpatterns = [
    path('', index, name="index"),
    path('employments', employment_list, name='employment_list'),
    path('jobseeker', job_seeker_list, name='job_seeker_list'),
    path('jobseeker/filter', seekers_filter, name='seeker_filter'),

    # employment
    path('employment/create', employment_create, name='employment_create'),
    path('employment/update/<int:job_id>', employment_update, name='employment_update'),
    path('employment/delete/<int:job_id>', employment_delete, name='employment_delete'),

    # seekers
    path('seeker/create', seeker_create, name='seeker_create'),
    path('seeker/update/<int:seeker_id>', seeker_update, name='seeker_update'),
    path('seeker/delete/<int:seeker_id>', seeker_delete, name='seeker_delete'),

]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('webapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from .views import *
app_name = "webapp"
urlpatterns = [
    path('', home, name="home"),
    path('login', login_request, name="login"),
    path('logout', logout_request, name="logout"),
    path('apply', apply_job, name="apply")
]

dashboard/models.py
from django.db import models
from datetime import datetime

now = datetime.now()
folder_path = str(now.strftime('%Y/%m/%d'))
LOGO_PATH = 'logo/' + folder_path
RESUME_PATH = 'resume/' + folder_path
# Create your models here.
STATUS_CHOICES = (
    ('International Students', 'International Students'),
    ('PR / Citizen', 'PR / Citizen')
)
AVAILABILITY_CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time')
)
EMPLOYMENT_TYPE = (
    ('Contract', 'Contract'),
    ('Permanent', 'Permanent')
)


class Employer(models.Model):
    class Meta:
        db_table = "Employer"
    job_title = models.CharField(max_length=250, blank=False, null=False)
    company = models.CharField(max_length=100)
    logo = models.ImageField(upload_to=LOGO_PATH)
    job_description = models.TextField()
    email = models.CharField(max_length=100)
    rate = models.DecimalField(default=0.0, max_digits=20, decimal_places=2)
    availability = models.CharField(max_length=30, choices=AVAILABILITY_CHOICES)
    duration = models.CharField(max_length=50)
    employment_type = models.CharField(max_length=30, choices=EMPLOYMENT_TYPE)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=30, blank=True, null=True)
    updated_by = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.job_title


class Employees(models.Model):
    class Meta:
        db_table = "Employees"
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=100)
    skill = models.CharField(max_length=50, blank=True, null=True)
    experience_year = models.IntegerField(default=0)
    phone_number = models.CharField(max_length=15)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES)
    availability = models.CharField(max_length=30, choices=AVAILABILITY_CHOICES)
    resume = models.FileField(upload_to=RESUME_PATH)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=30, blank=True, null=True)
    updated_by = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.email + ' -- ' + str(self.employer)


class Skills(models.Model):
    class Meta:
        db_table = "Skills"

    applicant_id = models.ForeignKey(Employees, on_delete=models.CASCADE)
    skill = models.CharField(max_length=50, blank=True, null=True)
    experience_year = models.IntegerField(default=0)

dashboard/forms.py
from django import forms
from .models import Employer, Employees


class EmploymentForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = ['job_title', 'company', 'logo', 'job_description', 'email', 'rate', 'availability', 'duration',
                  'employment_type', 'status', 'created_by', 'updated_by']
        widgets = {
            'created_by': forms.HiddenInput(),
            'updated_by': forms.HiddenInput(),
        }


class SeekerForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['employer', 'firstname', 'lastname', 'email', 'skill', 'experience_year', 'phone_number', 'status',
                  'availability', 'resume', 'created_by', 'updated_by']
        widgets = {
            'created_by': forms.HiddenInput(),
            'updated_by': forms.HiddenInput(),
        }

dashboard/views.py
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render, HttpResponse, redirect
from .db_helper import get_rows
from django.http import JsonResponse
from django.urls import reverse_lazy
from .forms import EmploymentForm, SeekerForm
from .models import Employer, Employees


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        if request.user.is_superuser or request.user.groups.filter(name="SecondAdmin").exists():
            return render(request, 'dashboard.html', context={})
        else:
            return redirect('webapp:home')
    return redirect('webapp:login')


# ----------------Employment------------------
def employment_list(request):
    if request.user.is_authenticated:
        if request.user.is_superuser or request.user.groups.filter(name="SecondAdmin").exists():
            sql = """
                SELECT id, 
                    job_title,
                    company,
                    logo,
                    job_description,
                    email,
                    rate,
                    availability,
                    duration,
                    employment_type,
                    status,
                    date(created_at) as created_at
                from Employer
            """

            if request.user.groups.filter(name="SecondAdmin") and not request.user.is_superuser:
                sql += "where created_by = '" + request.user.username + "'"
            results = get_rows(sql)
            context = {
                'data': json.dumps(results, cls=DjangoJSONEncoder),
                'page_title': "Employments"
            }
            return render(request, 'employments.html', context=context)
        return redirect('webapp:home')
    return redirect('webapp:login')


def employment_create(request):
    # TODO Error handling and optimization required
    if request.method == "GET":
        form = EmploymentForm()
        return render(request, 'employment_create.html', context={"form": form, "page_title": "Employment"})
    if request.method == "POST":
        form = EmploymentForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.created_by = request.user.username
            data.updated_by = None
            data.save()
        return redirect("dashboard:employment_list")


def employment_update(request, job_id):
    if request.method == "GET":
        form = EmploymentForm(instance=Employer.objects.get(id=job_id))
        context_data = {
            'form': form,
            'job_id': job_id,
            'page_title': "Employment"
        }
        return render(request, "employment_update.html", context=context_data)
    if request.method == "POST":
        instance = Employer.objects.get(id=job_id)
        form = EmploymentForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            data = form.save(commit=False)
            data.updated_by = request.user.username
            data.save()
        return redirect("dashboard:employment_list")


def employment_delete(request, job_id):
    instance = Employer.objects.get(id=job_id)
    instance.delete()
    return redirect("dashboard:employment_list")


# ----------------End of Employment------------------


# ----------------Employees------------------
def job_seeker_list(request):
    if request.user.is_authenticated:
        if request.user.is_superuser or request.user.groups.filter(name="SecondAdmin").exists():
            sql = """
                SELECT s.id,
                    s.firstname,
                    s.lastname,
                    s.email,
                    s.skill,
                    s.experience_year,
                    s.phone_number,
                    s.status,
                    s.availability,
                    s.resume,
                    s.employer_id
                FROM
                Employees as s
            """
            if not request.user.is_superuser:
                sql += "inner join Employer e " \
                       "on s.employer_id = e.id where e.created_by = '" + request.user.username + "'"
            results = get_rows(sql)
            data = json.dumps(results, cls=DjangoJSONEncoder)
            context = {
                'data': data,
                'page_title': "Candidates"
            }
            print(context['data'])
            return render(request, 'jobseekers.html', context=context)
        else:
            return redirect('webapp:home')
    return redirect('webapp:login')


def seeker_create(request):
    if request.method == "GET":
        form = SeekerForm()
        return render(request, 'seeker_create.html', context={"form": form, "page_title": "Candidate"})
    if request.method == "POST":
        form = SeekerForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.created_by = request.user.username
            data.updated_by = None
            data.save()
        return redirect("dashboard:job_seeker_list")


def seeker_update(request, seeker_id):
    if request.method == "GET":
        form = SeekerForm(instance=Employees.objects.get(id=seeker_id))
        context_data = {
            'form': form,
            'seeker_id': seeker_id,
            'page_title': "Candidate"
        }
        return render(request, "seeker_update.html", context=context_data)
    if request.method == "POST":
        instance = Employees.objects.get(id=seeker_id)
        form = SeekerForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            data = form.save(commit=False)
            data.updated_by = request.user.username
            data.save()
        return redirect("dashboard:job_seeker_list")


def seeker_delete(request, seeker_id):
    instance = Employees.objects.get(id=seeker_id)
    instance.delete()
    return redirect("dashboard:job_seeker_list")


# ----------------End of Employees------------------
def seekers_filter(request):
    # check if request params exists
    skills = request.GET.get('skills', '')
    years = request.GET.get('years', '')
    lastname = request.GET.get('lastname', '')
    query = """
        SELECT s.id,
            s.firstname,
            s.lastname,
            s.email,
            s.skill,
            s.experience_year,
            s.phone_number,
            s.status,
            s.availability,
            s.resume,
            s.employer_id
        FROM
        Employees s
        """
    if request.user.is_superuser:
       query += """
            WHERE lower(skill) like '%{0}%' and experience_year like '%{1}%' and lower(lastname) like '%{2}%';
        """.format(skills.lower() if skills else '', years if years else '', lastname.lower() if lastname else '')
    else:
        query += """ inner join Employer e
        on s.employer_id = e.id and e.created_by = '{0}'
        WHERE lower(skill) like '%{1}%' and experience_year like '%{2}%' and lower(lastname) like '%{3}%'; """\
        .format(request.user.username, skills.lower() if skills else '', years if years else '', lastname.lower() if lastname else '')
    results = get_rows(sql=query)
    data = json.dumps(results, cls=DjangoJSONEncoder)
    return JsonResponse({"status": 200, "data": data})

dashboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock title %} </title>
    <!-- Favicon icon -->
{#    <link rel="icon" type="image/png" sizes="16x16"  href="{% static 'plugins/images/favicon.png' %}">#}
    <!-- Custom CSS -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    {% block stylesheets  %} {% endblock stylesheets %}
</head>

<body>
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<!-- Main wrapper - style you can find in pages.scss -->
<div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
     data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
    <!-- Topbar header - style you can find in pages.scss -->
    <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-header" data-logobg="skin6">
                <a class="navbar-brand" href=".">
                    <!-- Logo icon -->
                    <b class="logo-icon">
                        <!-- Dark Logo icon -->
                        <img src= "{% static 'images/logo-icon.png' %}" alt="homepage" />
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                            <!-- dark Logo text -->
                        <b class="text-dark">JobPortal</b>
                        </span>
                </a>
                <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                   href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            </div>
            <!-- End Logo -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                <ul class="navbar-nav ms-auto d-flex align-items-center">
                    <!-- User profile -->
                   {% if request.user.is_authenticated %}
                       <li>
                       <div class="dropdown show">
                           <a class="dropdown-toggle profile-pic" href="#" role="button" data-toggle="dropdown" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">
                               <img src="{% static 'images/profile.jpg' %}" alt="user-img" width="36"
                                    class="img-circle"><span class="text-white font-medium">{{ request.user.username }}</span></a>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'webapp:logout' %}">Logout</a>
                          </div>
                        </div>


                       </li>
                    {% else %}
                       <a href="{% url 'webapp:home' %}">Login</a>{% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <!-- End Topbar header -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <!-- User Profile-->
                    <li class="sidebar-item pt-2">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:index' %}"
                           aria-expanded="false">
                            <i class="far fa-clock" aria-hidden="true"></i>
                            <span class="hide-menu">Dashboard</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:employment_list' %}"
                           aria-expanded="false">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="hide-menu">Employments</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:job_seeker_list' %}"
                           aria-expanded="false">
                            <i class="fa fa-table" aria-hidden="true"></i>
                            <span class="hide-menu">Candidates</span>
                        </a>
                    </li>
{#                    <li class="sidebar-item">#}
{#                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="#"#}
{#                           aria-expanded="false">#}
{#                            <i class="fa fa-info-circle" aria-hidden="true"></i>#}
{#                            <span class="hide-menu">Error 404</span>#}
{#                        </a>#}
{#                    </li>#}
                </ul>

            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- Page wrapper  -->
    <div class="page-wrapper">
        <!-- Bread crumb and right sidebar toggle -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Dashboard {% if page_title %} / {{ page_title }} {% endif %}</h4>
                </div>
            </div>
        </div>
        <!-- End Bread crumb and right sidebar toggle -->
        {% block body %} {% endblock body %}
        <!-- footer -->
        <footer class="footer text-center">
            @Copyright Job Portal
        </footer>
        <!-- End footer -->
    </div>
</div>
<!-- All Jquery -->
<script src="{% static 'plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!--Custom JavaScript -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %} {% endblock scripts %}
</body>

</html>

dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Job Portal | Dashboard {% endblock title %}
{% block stylesheets %} {% endblock stylesheets %}
{% block body %}
    <!-- Container fluid  -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12">
                <h1>Welcome to Job Portal. Use aside bar for the Navigation.</h1>
            </div>
        </div>
    </div>
    <!-- End Container fluid  -->
 {% endblock body %}
{% block scripts %} {% endblock scripts %}

dashboard/templates/employment_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Employment Create | JobPortal {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <div class="row col-sm-12">
                        <div class="col-sm-6">

                            <h3 class="box-title">Create New Employment</h3>
                        </div>
                    </div>
                    <div class="form-inline">

                        <form action="{% url 'dashboard:employment_create' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Add Employment" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock scripts %}
{% endblock body %}

dashboard/templates/employment_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Employment Create | JobPortal {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <div class="row col-sm-12">
                        <div class="col-sm-6">

                            <h3 class="box-title">Update Employment Information</h3>
                        </div>
                    </div>
                    <div class="form-inline">

                        <form action="{% url 'dashboard:employment_update' job_id=job_id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Update" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock scripts %}
{% endblock body %}

dashboard/templates/employments.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Employment | JobPortal {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
 {% endblock stylesheets %}

{% block body %}
<div class="container-fluid">
{#    <div class="row">#}
{#        <div class="col-sm-6"></div>#}
{#        <div class="col-sm-6 float-right">#}
{#            <form id="search_form">#}
{#                <div class="row form-inline">#}
{#                    <input class="form-control col" type="search" placeholder="Skills"  value='' aria-label="Search" name="skills">#}
{#                    <input class="form-control col" type="search" placeholder="Number of years" value='' aria-label="Search" name="years">#}
{#                    <input class="form-control col" type="search" placeholder="lastname" value="" aria-label="Search" name="lastname">#}
{#                    <button class="btn btn-outline-success col" type="submit" id="searchbar_button">Search</button>#}
{#                </div>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
    <br>
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <div class="row col-sm-12">
                    <div class="col-sm-6">

                        <h3 class="box-title">Employments List</h3>
                    </div>
                    <div class="col-sm-6">
                        <button id="add-employment" class="btn btn-outline-success my-2 my-sm-0 float-end" type="submit"><a href="{% url 'dashboard:employment_create' %}">Add Employment</a></button>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table text-nowrap" id="user_dataTable">
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
        <script src="{% static 'js/employment.js' %}"></script>
        <script>
            $(document).ready(function(){
                let data = {{ data|safe }};
                handler(data);
            });
        </script>
    {% endblock scripts %}
{% endblock body %}

dashboard/templates/jobseekers.html
{% extends 'base.html' %}
{% load static %}
{% block title %} JobSeekers | JobPortal {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
{% endblock stylesheets %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6 float-right">
                <form id="search_form">
                    <div class="row form-inline">
                        <input class="form-control col" type="search" placeholder="Skills" aria-label="Search"
                               name="skills">
                        <input class="form-control col" type="search" placeholder="Number of years"
                               aria-label="Search" name="years">
                        <input class="form-control col" type="search" placeholder="lastname"
                               aria-label="Search" name="lastname">
                        <button class="btn btn-outline-success col" type="submit" id="seeker_search_button">Search</button>
                    </div>
                </form>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <div class="row col-sm-12">
                        <div class="col-sm-6">
                            <h3 class="box-title">Candidate List</h3>
                        </div>
                        <div class="col-sm-6">
                            <button id="add-seekers" class="btn btn-outline-success my-2 my-sm-0 float-end" type="submit"><a href="{% url 'dashboard:seeker_create' %}">Add Job Seekers</a></button>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-nowrap" id="job_seekers_dataTable">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" charset="utf8"
                src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
        <script src="{% static 'js/seekers.js' %}"></script>
        <script>
            $(document).ready(function () {
                let data = {{ data|safe }};
                handler(data);
            });
        </script>
    {% endblock scripts %}
{% endblock body %}

dashboard/templates/seeker_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Job Seekers Create | JobPortal {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <div class="row col-sm-12">
                        <div class="col-sm-6">

                            <h3 class="box-title">Add Candidate Manually</h3>
                        </div>
                    </div>
                    <div class="form-inline">

                        <form action="{% url 'dashboard:seeker_create' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Add" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock scripts %}
{% endblock body %}

dashboard/templates/seeker_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Seeker Update | JobPortal {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <div class="row col-sm-12">
                        <div class="col-sm-6">

                            <h3 class="box-title">Update Candidate's Information</h3>
                        </div>
                    </div>
                    <div class="form-inline">

                        <form action="{% url 'dashboard:seeker_update' seeker_id=seeker_id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Update" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script type="application/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock scripts %}
{% endblock body %}